const CLICK_YOUTUBE = 'CLICK_YOUTUBE';
const CLICK_FACEBOOK = 'CLICK_FACEBOOK';
const CLICK_YOUTUBE_CHANNEL = 'CLICK_YOUTUBE_CHANNEL';
const CLICK_YOUTUBE_MEDIA = 'CLICK_YOUTUBE_MEDIA';

export const actionTypes = {
  CLICK_FACEBOOK,
  CLICK_YOUTUBE,
  CLICK_YOUTUBE_CHANNEL,
  CLICK_YOUTUBE_MEDIA
}